name = "Noelle Pack 1.19.2"
author = "eff3ry, Nolliewee"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae5f12dff4d4507b6a5289fa669ec9b95f27a3d383b52807ac7ce859f038ceba"

[versions]
forge = "43.4.2"
minecraft = "1.19.2"
