name: CF_Pack

on:
  push:
    branches: [ "main", "workflow-testing" ]
  pull_request:
    branches: [ "main", "workflow-testing" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Runs the packwiz command to export the CurseForge pack
      - name: Export pack as CurseForge pack
        run: ./packwiz.exe cf export

      # Unzip the generated CurseForge pack
      - name: Unzip CurseForge pack
        run: |
          mkdir extracted_pack
          unzip *.zip -d extracted_pack
          rm *.zip
      
      # Get the commit ID and save it to an environment file
      - name: Get commit ID
        id: get_commit
        run: echo "commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Rename the folder with the commit ID
      - name: Rename folder with commit ID
        shell: bash
        run: |
          VERSION=$(basename *.zip | sed 's/.*-\(.*\)\.zip/\1/')
          mv extracted_pack NoelleCraft-1.19.2-${VERSION}-${commit_id}
      # List the contents of the directory for debugging using PowerShell
      - name: Debug - List files
        run: Get-ChildItem -Recurse

      # Upload the folder as an artifact
      - uses: actions/upload-artifact@v4
        with:
          name: NoelleCraft-1.19.2-${VERSION}-${commit_id}
          path: NoelleCraft-1.19.2-${VERSION}-${commit_id}
