name: CF_Pack

on:
  push:
    branches: [ "main", "workflow-testing" ]
  pull_request:
    branches: [ "main", "workflow-testing" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Runs the packwiz command to export the CurseForge pack
      - name: Export pack as CurseForge pack
        run: ./packwiz.exe cf export

      # Extract the version number from the ZIP file name (improved)
      - name: Extract Version Number
        shell: bash
        run: |
          VERSION=${basename *.zip | cut -d '-' -f 2%-*}  # Extract second field (version)
          echo "VERSION=$VERSION"  # Print for debugging

      # Unzip the generated CurseForge pack
      - name: Unzip CurseForge pack
        shell: bash
        run: |
          mkdir extracted_pack
          unzip *.zip

      # Get the commit ID and save it to an environment file
      - name: Get commit ID
        shell: bash
        id: get_commit
        run: echo "commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Rename the folder with version and commit ID
      - name: Rename folder with version and commit ID
        shell: bash
        run: |
          mv NoelleCraft-1.19.2-${VERSION} "NoelleCraft-1.19.2-${VERSION}-${{ env.commit_id }}"

      # Debugging to check values (optional)
      - name: Debugging - Check Variables
        shell: bash
        run: |
          echo "VERSION: $VERSION"
          echo "commit_id: ${{ env.commit_id }}"

      # Upload the folder as an artifact
      - uses: actions/upload-artifact@v4
        with:
          name: "NoelleCraft-1.19.2-${VERSION}-${{ env.commit_id }}"
          path: "NoelleCraft-1.19.2-${VERSION}-${{ env.commit_id }}"
