name: Build and Upload Modpack

on:
  push:
    branches:
      - main
      - workflow-testing

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Extract modpack
        run: |
          mkdir extracted_pack
          Expand-Archive -Path "Noelle Pack 1.19.2-1.0.7.zip" -DestinationPath extracted_pack

      - name: Get commit ID
        run: echo "commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Rename extracted directory
        run: |
          $newDirName = "NoelleCraft-1.19.2_$env:commit_id"
          Rename-Item -Path "extracted_pack" -NewName $newDirName

      - name: Upload modpack
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.get_commit_id.outputs.commit_id }}_modpack
          path: $newDirName
